In [100]:
'''
Katelyn Choudhari
COP4283
Script Assignment 1A
'''

#Script 1
'''
Original code with error:
a = "this is a string"
a[10] = "f"
'''

#Solution - using slicing:
a = "this is a string"
a = a[:10] + "f" + a[11:]
print(a)

this is a ftring


In [102]:
#Script 2
'''
Original code with error:
a_tuple = (3, 5, (4, 5))
a_tuple[1] = "four"
'''

#Solution - creating a new tuple to insert the str 'four'
a_tuple = (3, 5, (4, 5))
a_tuple = (a_tuple[0], "four", a_tuple[2])
print(a_tuple)

(3, 'four', (4, 5))


In [104]:
#Script 3
'''
Original code with error:
"5" + 5
'''

#Solution - convert data types to concatenate strings or do addition of integers
#Depending on what you need the code to do, it will yield different outputs
stringConcatenation = "5" + str(5)
print(stringConcatenation)

#-or-

integerAddition = int("5") + 5
print(integerAddition)

55
10


In [106]:
#Script 4
'''
Original code
import numpy as np
np.random.seed(12345)
np.set_printoptions(precision=4, suppress=True)
'''

#Solution - generate 5 random numbers and output values
import numpy as np
np.random.seed(12345) #setting a seed ensures the same random values are outputted every time
np.set_printoptions(precision=4, suppress=True)
decimalValues = np.random.randn(5)
print(decimalValues)

#Not setting a seed will output different values each time
import numpy as np
np.random.seed() 
np.set_printoptions(precision=4, suppress=True)
decimalValues = np.random.randn(5)
print(decimalValues)

#-or-

import numpy as np
print(np.random.rand(5))

[-0.2047  0.4789 -0.5194 -0.5557  1.9658]
[ 0.5954  0.7371  0.0337 -0.9586 -0.4635]
[0.2047 0.6194 0.5016 0.0612 0.3944]


In [108]:
#Script 5
'''
Original code
s = "3.14159"
fval = float(s)
type(fval)
int(fval)
bool(fval)
bool(0)
'''

#Solution - outputs what each line does
s = "3.14159"
fval = float(s)
type(fval)
int(fval)
bool(fval)
bool(0)

print(fval)        #Convert str to a float 
print(type(fval))  #Return data type/class of the variable
print(int(fval))   #Convert float to int
print(bool(fval))  #Boolean true
print(bool(0))     #Boolean false

3.14159
<class 'float'>
3
True
False
